from tkinter import *
from tkinter import messagebox
a=Tk()
a.title('Infosys')

b=StringVar()
c=StringVar()
d=StringVar()
e=StringVar()
f=StringVar()
g=StringVar()
h=StringVar()
i=StringVar()
j=StringVar()
k=StringVar()
l=StringVar()
m=StringVar()
n=StringVar()
def fileopen():
    messagebox.showinfo(text="Saving",messagebox="Saved")
def dele():
    m=messagebox.showinfo(text="Deleting",message="Deleted")
    if(m==1):
        a.destroy()

a.geometry('500x500+100+100')
mylabel1=Label(text='Infosys Registration',fg='blue',bg='black',font=10).pack()
mylabel2=Label(text='First Name:',fg='black',bg='white',font=5).place(x=50,y=50)
text1=Entry(a,textvariable=b).place(x=50,y=70)
mylabel3=Label(text='Middle Name:',fg='black',bg='white',font=5).place(x=50,y=110)
text2=Entry(a,textvariable=c).place(x=50,y=130)
mylabel4=Label(text='Last Name:',fg='black',bg='white',font=5).place(x=50,y=160)
text3=Entry(a,textvariable=d).place(x=50,y=180)
mylabel5=Label(text='Date Of Birth:',fg='black',bg='white',font=5).place(x=50,y=210)
text4=Entry(a,textvariable=e).place(x=50,y=230)
mylabel6=Label(text='Father Full Name:',fg='black',bg='white',font=5).place(x=50,y=260)
text5=Entry(a,textvariable=f).place(x=50,y=280)
mylabel7=Label(text='Mother Full Name:',fg='black',bg='white',font=5).place(x=50,y=310)
text6=Entry(a,textvariable=g).place(x=50,y=330)
mylabel8=Label(text='Phone Number:',fg='black',bg='white',font=5).place(x=50,y=360)
text7=Entry(a,textvariable=h).place(x=50,y=380)
mybutton1=Button(text='Submit',fg='black',bg='blue',width=15,command=fileopen,font=10).place(x=50,y=420)
mylabel9=Label(text='Address:',fg='black',bg='white',font=5).place(x=250,y=50)
text8=Entry(a,textvariable=i).place(x=250,y=70)
mylabel10=Label(text='PinCode:',fg='black',bg='white',font=5).place(x=250,y=100)
text9=Entry(a,textvariable=j).place(x=250,y=130)
mylabel11=Label(a,text='State Name:',fg='black',bg='white',font=5).place(x=250,y=160)
text10=Entry(a,textvariable=k).place(x=250,y=190)
mylabel12=Label(a,text='Country Name:',fg='black',bg='white',font=5).place(x=250,y=220)
text12=Entry(a,textvariable=l).place(x=250,y=250)
mylabel13=Label(a,text='Place:',fg='black',bg='white',font=5).place(x=250,y=290)
text12=Entry(a,textvariable=m).place(x=250,y=330)
mylabel14=Label(a,text='Date:',fg='black',bg='white',font=5).place(x=250,y=360)
text13=Entry(a,textvariable=n).place(x=250,y=380)
mybutton2=Button(text='Cancel',fg='black',bg='blue',width=15,command=dele,font=10).place(x=250,y=420)
a.mainloop()
